# WRITE A PROGRAM TO PREFORM DIFFERENT ARITHMETIC OPERATIONS ON NUMBERS IN PYTHON.
# Program to perform different arithmetic operations

# Taking input from user
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

# Performing arithmetic operations
print("Addition:", num1 + num2)
print("Subtraction:", num1 - num2)
print("Multiplication:", num1 * num2)
print("Division:", num1 / num2)
print("Floor Division:", num1 // num2)
print("Modulus:", num1 % num2)
print("Exponentiation:", num1 ** num2)
